name: Deploy to Live Channel

on:
  push:
    branches:
      - main    

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx playwright install --with-deps
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: blog-f59d2
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks