name: Deploy to Live Channel

on:
  push:
    branches:
      - main

jobs:
  deploy_live_website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx -y playwright@1.51.1 install --with-deps chromium
      - run: npm run test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: blog-f59d2
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          MODE: production
